# This file is used as a base for all other repositories in the Homebrew GitHub
# organisation so intentionally contains package-ecosystems that do not apply to
# this repository.
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    # The actions in triage-issues.yml are updated in the Homebrew/.github repo
    ignore:
      - dependency-name: actions/stale
    groups:
      artifacts:
        patterns:
          - actions/*-artifact

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
