# This file is used as a base for all other repositories in the Homebrew GitHub
# organisation so intentionally contains package-ecosystems that do not apply to
# this repository. They will be stripped out if unneeded by the sync action.
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: "friday"
      time: "08:00"
      timezone: "Etc/UTC"
    allow:
      - dependency-type: all
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: bundler
    directories:
      - /
      - /Library/Homebrew
    schedule:
      interval: weekly
      day: "friday"
      time: "08:00"
      timezone: "Etc/UTC"
    allow:
      - dependency-type: all
    groups:
      bundler:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: "friday"
      time: "08:00"
      timezone: "Etc/UTC"
    allow:
      - dependency-type: all
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: "friday"
      time: "08:00"
      timezone: "Etc/UTC"
    allow:
      - dependency-type: all
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
      day: "friday"
      time: "08:00"
      timezone: "Etc/UTC"
    allow:
      - dependency-type: all
    groups:
      devcontainers:
        patterns:
          - "*"

  - package-ecosystem: pip
    directories:
      - /
      - /Library/Homebrew/formula-analytics/
    schedule:
      interval: weekly
      day: "friday"
      time: "08:00"
      timezone: "Etc/UTC"
    allow:
      - dependency-type: all
    groups:
      pip:
        patterns:
          - "*"
