name: Sync shared configurations

on:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: sync-shared-config
  cancel-in-progress: true

jobs:
  sync-shared-config:
    if: github.repository == 'Homebrew/.github'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - Homebrew/.github
          - Homebrew/actions
          - Homebrew/brew
          - Homebrew/brew-pip-audit
          - Homebrew/brew.sh
          - Homebrew/ci-orchestrator
          - Homebrew/discussions
          - Homebrew/formula-patches
          - Homebrew/formulae.brew.sh
          - Homebrew/glibc-bootstrap
          - Homebrew/homebrew-aliases
          - Homebrew/homebrew-bundle
          - Homebrew/homebrew-cask
          - Homebrew/homebrew-command-not-found
          - Homebrew/homebrew-core
          - Homebrew/homebrew-formula-analytics
          - Homebrew/homebrew-linux-fonts
          - Homebrew/homebrew-portable-ruby
          - Homebrew/homebrew-services
          - Homebrew/homebrew-test-bot
          - Homebrew/install
          - Homebrew/mass-bottling-tracker
          - Homebrew/orka_api_client
          - Homebrew/ruby-macho
          - Homebrew/rubydoc.brew.sh
      fail-fast: false
    steps:
      - name: Clone main repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clone secondary repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          path: vendor/${{ matrix.repo }}
          persist-credentials: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: BrewTestBot

      - name: Set up GPG commit signing
        uses: Homebrew/actions/setup-commit-signing@master
        with:
          signing_key: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY }}

      - name: Detect changes
        id: detect_changes
        env:
          HOMEBREW_GPG_PASSPHRASE: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY_PASSPHRASE }}
        run: ./.github/actions/sync/shared-config.rb 'vendor/${{ matrix.repo }}' '${{ matrix.repo }}' 'sync-shared-config'

      - name: Create pull request
        if: ${{ steps.detect_changes.outputs.pull_request == 'true' }}
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e
        with:
          path: vendor/${{ matrix.repo }}
          token: ${{ secrets.HOMEBREW_DOTGITHUB_WORKFLOW_TOKEN }}
          branch: sync-shared-config
          title: Synchronize shared configuration
          body: >
            This pull request was created automatically by the
            [`sync-shared-config`](https://github.com/Homebrew/.github/blob/HEAD/.github/workflows/sync-shared-config.yml)
            workflow.
